server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql: TRACE
    com.gitlab.devmix.warehouse.core.impl.controlles.EntityApiControllerImpl: TRACE

spring:
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update

  datasource:
    url: jdbc:h2:./db/sam
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false

---

spring:
  profiles: postgres
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
#    hibernate.ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse
    username: root
    password: root
    driverClassName: org.postgresql.Driver
---

spring:
  profiles: mariadb
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
#    hibernate.ddl-auto: create-drop
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mariadb://localhost:3306/warehouse
    username: root
    password: root
    driverClassName: org.mariadb.jdbc.Driver