server:
  port: 8080

logging:
  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE
    org.hibernate.cache: INFO
    org.hibernate.stat: DEBUG
#    org.hibernate.type.descriptor.sql: TRACE
    com.gitlab.devmix.warehouse.core.impl.controlles.EntityApiControllerImpl: TRACE

spring:
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
#    properties.hibernate.generate_statistics: true
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
        jdbc:
          batch_size: 100
          fetch_size: 100

  datasource:
#    url: jdbc:h2:./db/sam
#    driverClassName: org.h2.Driver
    url: jdbc:p6spy:h2:./db/sam
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    platform: h2
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false

---

spring:
  profiles: postgres
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
#    hibernate.ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse
    username: root
    password: root
    driverClassName: org.postgresql.Driver
---

spring:
  profiles: mariadb
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
#    hibernate.ddl-auto: create-drop
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mariadb://localhost:3306/warehouse
    username: root
    password: root
    driverClassName: org.mariadb.jdbc.Driver